export const DISPLAY_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const PASSWORD_UNMATCH = "PASSWORD_UNMATCH"

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"